name: Deploy to EC2

on:
  push:
    branches:
      - main  # Nome da branch que acionará o deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload JAR to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: 'hostfullyChallenge-0.0.1-SNAPSHOT.jar'
        target: '~/app/'

    - name: Execute JAR on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          pkill -f 'java -jar' || true
          nohup java -jar ~/hostfullyChallenge/hostfullyChallenge-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
