name: Deploy to EC2

on:
  push:
    branches:
      - main  # The branch that will trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Ensure you are using the correct version

      - name: Build project
        run: |
          ./gradlew build  # Ensure this command generates the JAR file in the correct location

      - name: List files for debug
        run: ls -al build/libs/

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: 'build/libs/hostfullyChallenge-0.0.1-SNAPSHOT.jar'  # Ensure this path is correct
          target: '~/hostfullyChallenge/'

      - name: Execute JAR on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            pkill -f 'java -jar' || true
            nohup java -jar ~/hostfullyChallenge/hostfullyChallenge-0.0.1-SNAPSHOT.jar > ~/hostfullyChallenge/app.log 2>&1 &
